name: Auto Versioning

on:
  push:
    branches: [main]

jobs:
  version-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Update version
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          current=$(cat version.txt)
          new_version=$(echo $current | awk -F. '{$NF+=1; OFS="."; print $0}')
          echo $new_version > version.txt
          git add version.txt
          git commit -m "ci: auto update version to $new_version"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
