name: Auto Versioning

on:
  push:
    branches: [main]

jobs:
  version-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Update version
        run: |
          git config user.name "CI Bot"
          git config user.email "ci-bot@users.noreply.github.com"
          current=$(cat version.txt)
          new_version=$(echo $current | awk -F. '{$NF+=1; OFS="."; print $0}')
          echo $new_version > version.txt
          git add version.txt
          git commit -m "CI: Update version to $new_version"
          git push
