name: Auto Versioning

on:
  push:
    branches: [main]

jobs:
  version-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Display current version
        run: |
          echo "Current version: $(cat version.txt)"
          current=$(cat version.txt | sed 's/v//')
          IFS='.' read -r major minor patch <<< "$current"
          new_patch=$((patch + 1))
          new_version="v${major}.${minor}.${new_patch}"
          echo "Next version would be: $new_version"
          echo "::set-output name=new_version::$new_version"
